services:
  # ----------------------------
  # 1. PostgreSQL + UI (PgAdmin)
  # ----------------------------
  postgres:
    image: postgres:15-alpine
    container_name: notif_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: notification_users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notif-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: notif_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - notif-network

  # ----------------------------
  # 2. Redis + UI (RedisInsight)
  # ----------------------------
  redis:
    image: redis/redis-stack:latest
    container_name: notif_redis
    ports:
      - "6379:6379"  # Redis Port
      - "8001:8001"  # RedisInsight UI Port
    networks:
      - notif-network

  # ----------------------------
  # 3. DynamoDB + UI
  # ----------------------------
  dynamodb:
    image: amazon/dynamodb-local
    container_name: notif_dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    networks:
      - notif-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: notif_dynamodb_ui
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "us-east-1"
    ports:
      - "8002:8001" # Mapped to 8002 because Redis uses 8001
    depends_on:
      - dynamodb
    networks:
      - notif-network

  # ----------------------------
  # 4. Kafka (Kraft) + UI
  # ----------------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: notif_kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # This line allows your Host (Node.js) to talk to 'localhost:9092'
      # And Docker containers (Kafka UI) to talk to 'kafka:29092'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      start_period: 15s
      interval: 5s
      retries: 10
    networks:
      - notif-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: notif_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - notif-network

volumes:
  postgres_data:
  dynamodb_data:

networks:
  notif-network:
    driver: bridge